### ISSUE TITLE
[kinetic] abroot kargs throws out of range error

### ISSUE THREAD

**Issue by wiesenklee** [Vanilla-OS/ABRoot#56]
Running 'VanillaOS 22.10 all' with kernel version 5.19.0-38-generic.

Reproduce:
- Open Bash Shell in Gnome Console
- running `$ abroot kargs`

Full log:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/vanilla-os/abroot/cmd.kargsCommand(0xc000195200?, {0xac3f50?, 0x0?, 0x0?})
	github.com/vanilla-os/abroot/cmd/kargs.go:20 +0x43e
github.com/vanilla-os/abroot/vendor/github.com/spf13/cobra.(*Command).execute(0xc000195200, {0xac3f50, 0x0, 0x0})
	github.com/vanilla-os/abroot/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/vanilla-os/abroot/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000194000)
	github.com/vanilla-os/abroot/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/vanilla-os/abroot/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	github.com/vanilla-os/abroot/vendor/github.com/spf13/cobra/command.go:968
github.com/vanilla-os/abroot/vendor/github.com/vanilla-os/orchid/cmdr.(*App).Run(0xc000194000?)
	github.com/vanilla-os/abroot/vendor/github.com/vanilla-os/orchid/cmdr/app.go:94 +0x78
main.main()
	github.com/vanilla-os/abroot/main.go:48 +0x953
```

**Comment by taukakao** [comment]
I can't  reproduce this. Is this still an issue?
